# Generated by Django 5.2.3 on 2025-07-09 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamesession',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userstats',
            name='user',
        ),
        migrations.DeleteModel(
            name='GameRound',
        ),
        migrations.DeleteModel(
            name='GameSession',
        ),
        migrations.DeleteModel(
            name='UserStats',
        ),
    ]
