# Generated by Django 5.2.3 on 2025-07-09 00:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('playlist_id', models.CharField(max_length=100)),
                ('playlist_name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('total_rounds', models.IntegerField(default=0)),
                ('correct_guesses', models.IntegerField(default=0)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GameRound',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('track_id', models.CharField(max_length=100)),
                ('track_name', models.CharField(max_length=200)),
                ('artist_name', models.CharField(blank=True, max_length=200)),
                ('preview_url', models.URLField()),
                ('user_guess', models.CharField(blank=True, max_length=200)),
                ('is_correct', models.BooleanField(null=True)),
                ('time_taken', models.FloatField(null=True)),
                ('round_number', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='api.gamesession')),
            ],
        ),
        migrations.CreateModel(
            name='UserStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_games_played', models.IntegerField(default=0)),
                ('total_rounds_played', models.IntegerField(default=0)),
                ('total_correct_guesses', models.IntegerField(default=0)),
                ('best_score_percentage', models.FloatField(default=0.0)),
                ('average_time_per_guess', models.FloatField(default=0.0)),
                ('last_played', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
